#!/bin/bash
#
# Makes a .zip for submission

id=24

# check that the code compiles
make -j10

# removing old archive
rm $id.zip

# removes log files
rm *.out

# creating the directory and copying data inside
mkdir $id
cp *.h *.cpp Makefile $id/

# adding lcb algo and proof 
mkdir $id/lcb_algo
cp lcb_algo/main.pdf lcb_algo/main.tex $id/lcb_algo/

# adding our tests
mkdir $id/tests
cp -r tests/*.ipynb tests/test_localized_causal_all_properties.py tests/run_with_crashes.py tests/run_performance.py tests/test_fifo_all_properties.py tests/tests_for_tests $id/tests/

# zip to submit
zip -r $id.zip $id

# removing the directory
rm -rf $id
