#!/bin/bash
#
# Makes a .zip for submission

id=24

# check that the code compiles
make -j10

# removing old archive
rm $id.zip

# removes log files
rm *.out

# creating the directory and copying data inside
mkdir $id
cp *.h *.cpp Makefile $id/

# adding lcb algo and proof 
cp -r lcb_algo $id/

# adding our tests
mkdir $id/tests
cp tests/test_localized_causal_all_properties.py tests/run_with_crashes.py $id/tests/

# zip to submit
zip -r $id.zip $id

# removing the directory
rm -rf $id
