#!/bin/bash
#
# Makes a .zip for submission

id=24

# check that the code compiles
make -j10

# removing old archive
rm $id.zip

# removes log files
rm *.out

# creating the directory and copying data inside
mkdir $id
cp *.h *.cpp Makefile $id/

# zip to submit
zip -r $id.zip $id

# removing the directory
rm -rf $id
